# Generated by Django 4.2.13 on 2024-05-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Database",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("time", models.TimeField(auto_now_add=True)),
                ("Latitude", models.IntegerField(max_length=3)),
                ("Image_File", models.ImageField(upload_to="images")),
                ("Predicted_Intensity", models.IntegerField()),
            ],
        ),
    ]
